version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongoDB-Saif
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - volume1:/data/db


  mongo-express:
    image: mongo-express
    container_name: mongoExpress-Saif
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDB-Saif
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - mongo-network

networks:
  mongo-network:
volumes:
  volume1:
   name: volume1
